language: php

env:
    global:
        - REDIS_HOST=localhost
        - MONGO_HOST=localhost

services:
  - redis-server
  - mongodb

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - vendor/bin/codacycoverage clover build/logs/clover.xml
