language: php

env:
    global:
        - REDIS_HOST=localhost
        - MONGO_HOST=localhost

services:
  - redis-server
  - mongodb

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
    fast_finish: true

before_install:
  - if [[ $PHP != hhvm ]]; then pecl install mongodb; fi
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer self-update
  - composer install --prefer-dist

script:
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - vendor/bin/codacycoverage clover build/logs/clover.xml
